language: node_js
node_js:
- '6'
- '8'
- '10'
sudo: false
script:
- 'npm test'
after_success:
- 'nyc report --reporter=lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage && rm -rf ./.nyc_output'
